/* EXECUTIVE_NARRATIVE_COMPOSER_V20_3_1 */
(function(){
'use strict';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const A=v=>Array.isArray(v)?v:[];
const has=v=>v!=null&&v!==''&&!(Array.isArray(v)&&!v.length);
const clean=v=>String(v??'').replace(/Ãƒâ€šÃ‚Â·|Ã‚Â·/g,' â€¢ ').replace(/ÃƒÂ°Ã…Â¸Ã…Â¸Ã‚Â¢/g,'High').replace(/ÃƒÂ°Ã…Â¸Ã…Â¸Ã‚Â¡/g,'Medium').replace(/ÃƒÂ°Ã…Â¸Ã¢â‚¬Ã‚Â´/g,'Low').replace(/ÃƒÂ¢Ã…Â¡Ã‚Âª/g,'Unverified').replace(/\s+/g,' ').trim();
const safeUrl=v=>{try{const u=new URL(String(v));return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const icon=v=>{const s=clean(v).toLowerCase();if(/high|verified|confirmed/.test(s))return'&#x1F7E2;';if(/medium|partial|hypothesis/.test(s))return'&#x1F7E1;';if(/low|risk/.test(s))return'&#x1F534;';return'&#x26AA;'};
const proseMap={why_it_matters:'This matters because',customer_outcome:'The intended customer outcome is',partner_or_client_value:'The primary business value is',subject_value:'The customer value is',black_duck_value:'Black Duck provides',black_duck_contribution:'Black Duck contributes',commercial_or_mission_impact:'The expected mission and business impact is',partnership_implication:'The partnership implication is',joint_action:'The recommended joint action is',next_step:'The next recommended action is',first_action:'The first action is',black_duck_response:'Black Duck should respond by',success_measure:'Success should be measured through',success_criterion:'Success should be measured through',success_measures:'Success should be measured through',owner:'The proposed owner is',timing:'The expected timing is',period:'The expected period is',procurement_path:'The likely procurement path is',black_duck_entry:'Black Duck can enter by'};
const titleKeys=['title','headline','name','theme','factor','pillar','element','stakeholder','capability','dimension','action','development'];
const skip=new Set([...titleKeys,'source_url','url','confidence','status','verification_status','classification','date_verified']);
function sentence(k,v){const t=clean(v);if(!t)return'';const key=String(k).toLowerCase();if(['description','analysis','assessment','significance','effect','scope','problem','opening','recommendation','response','approach','verified_fact_or_context','evidence','exact_quote','differentiation_or_complementarity'].includes(key))return t;const lead=proseMap[key];return lead?lead+' '+t.charAt(0).toLowerCase()+t.slice(1):t;}
function title(o,i){return titleKeys.map(k=>o&&o[k]).find(has)||'Insight '+(i+1)}
function renderValue(k,v){
 if(Array.isArray(v)){if(!v.length)return'';if(v.every(x=>typeof x!=='object'))return'<ul>'+v.map(x=>'<li>'+E(clean(x))+'</li>').join('')+'</ul>';return v.map((x,i)=>window.v18ProseItem(x,i,true)).join('')}
 if(v&&typeof v==='object')return Object.entries(v).filter(([,x])=>has(x)).map(([a,x])=>renderValue(a,x)).join('');
 const s=sentence(k,v);return s?'<p>'+E(s)+( /[.!?]$/.test(s)?'':'.')+'</p>':'';
}
window.v18ProseItem=function(item,index){
 if(item==null)return'';if(typeof item!=='object')return'<article class="v203-card"><p>'+E(clean(item))+'</p></article>';
 const body=Object.entries(item).filter(([k,v])=>!skip.has(k)&&has(v)).map(([k,v])=>renderValue(k,v)).join('');
 const confidence=item.confidence||item.verification_status||item.classification||item.status||'Unverified';
 const urls=[item.source_url,item.url].filter(safeUrl);
 return '<article class="v203-card"><h3>'+E(title(item,index))+'</h3>'+(body||'<p>No narrative detail was supplied.</p>')+'<div class="v203-meta"><span class="v203-confidence">'+icon(confidence)+' '+E(clean(confidence))+' Confidence</span>'+urls.map(u=>'<a class="v203-source" href="'+E(safeUrl(u))+'" target="_blank" rel="noopener noreferrer">&#x1F517; View source</a>').join(' ')+'</div></article>';
};
const st=document.createElement('style');st.textContent=`
.v203-card .v203-card{margin:10px 0;background:rgba(255,255,255,.07);box-shadow:none}.v203-card p{font-size:11.5pt;line-height:1.66}.v203-card ul{padding-left:22px}.v203-card .v203-confidence{background:#5a3c72}.v2031-wrap{max-width:1280px;margin:auto}.v2031-hero{background:#6b4a86;border:1px solid #b59ac9;border-radius:14px;padding:22px;margin-bottom:15px}.v2031-hero p{color:#f0e8f5}.v2031-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.v2031-card{background:#795894;border:1px solid #b59ac9;border-left:5px solid #ffd166;border-radius:14px;padding:19px;margin-bottom:14px;color:#fff}.v2031-card h2{color:#fff;margin-top:0}.v2031-card p,.v2031-card li{color:#fff;line-height:1.62}.v2031-score{font-size:40px;font-weight:900;color:#ffd166}.v2031-actions{display:flex;gap:8px;flex-wrap:wrap}.v2031-tag{display:inline-block;background:#5a3c72;border:1px solid #b59ac9;border-radius:999px;padding:4px 9px;margin:2px}.v2031-opener{background:rgba(31,12,45,.24);border-left:4px solid #8ff0e8;padding:12px}.v2031-table{width:100%;border-collapse:collapse}.v2031-table td,.v2031-table th{position:static!important;border:1px solid #b59ac9;padding:9px;text-align:left;vertical-align:top}@media(max-width:900px){.v2031-grid{grid-template-columns:1fr}}`;
document.head.appendChild(st);
const card=(t,b)=>'<section class="v2031-card"><h2>'+E(t)+'</h2>'+b+'</section>';
const paragraphs=v=>clean(v).split(/\n\s*\n/).filter(Boolean).map(x=>'<p>'+E(x)+'</p>').join('');
const bullets=(v,f=x=>E(clean(x)))=>'<ul>'+A(v).map(x=>'<li>'+f(x)+'</li>').join('')+'</ul>';
window.openExecutiveStrategyV20=async function(id){
 window.__v20id=id;if(typeof route==='function')route('executivestrategy');const out=document.getElementById('executivestrategyView');out.innerHTML=card('Executive Strategy','<p>Building executive narrative...</p>');
 try{const r=await fetch('/api/executive-strategy-v20/'+encodeURIComponent(id));const x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');const people=A(x.stakeholder_map);
 out.innerHTML='<div class="v2031-wrap"><div class="v2031-hero"><div class="v2031-actions"><button onclick="route(\'history\')">Back to History</button><button id="v2031Refresh">Regenerate</button></div><h1>'+E(x.partner||'Partner')+' + '+E(x.account||'Account')+' Executive Brief</h1><span class="v2031-tag">Stage '+E(clean(x.stage))+'</span><span class="v2031-tag">V20.3.1</span></div>'+card('Executive Assessment',paragraphs(x.executive_summary))+ '<div class="v2031-grid">'+card('Why Now',paragraphs(x.why_now))+card('Executive Readiness','<div class="v2031-score">'+E(x.readiness&&x.readiness.score)+'%</div><p>'+E(x.readiness&&x.readiness.status)+'</p>')+'</div>'+card('Mission Outcome and Risk','<p>'+E(clean(x.mission_outcome||'Not yet evidenced.'))+'</p><h3>Consequence of failure</h3><p>'+E(clean(x.consequence_of_failure||'Not yet evidenced.'))+'</p>')+card('Executive Opener','<div class="v2031-opener"><p><strong>Data:</strong> '+E(clean(x.executive_opener&&x.executive_opener.data))+'</p><p><strong>Insight:</strong> '+E(clean(x.executive_opener&&x.executive_opener.insight))+'</p><p><strong>Question:</strong> '+E(clean(x.executive_opener&&x.executive_opener.question))+'</p></div>')+'<div class="v2031-grid">'+card('Business Drivers',bullets(x.themes,v=>'<strong>'+E(clean(v.headline))+'</strong><br>'+E(clean(v.why))))+card('Strategic Risks',bullets(x.challenges,v=>'<strong>'+E(clean(v.title))+'</strong><br>'+E(clean(v.description))))+'</div>'+card('Stakeholder Strategy',people.length?'<table class="v2031-table"><thead><tr><th>Stakeholder</th><th>Role</th><th>Influence</th><th>Next move</th></tr></thead><tbody>'+people.map(v=>'<tr><td>'+E(clean(v.name))+'</td><td>'+E(clean(v.role))+'</td><td>'+E(clean(v.influence))+'</td><td>'+E(clean(v.next))+'</td></tr>').join('')+'</tbody></table>':'<p>No stakeholder evidence captured.</p>')+'<div class="v2031-grid">'+card('Lighthouse Opportunity',paragraphs(x.lighthouse))+card('Success Measures and Gaps',bullets(x.evidence_gaps))+'</div>'+card('Action Plan',bullets(x.recommended_actions,v=>'<strong>'+E(clean(v.action))+'</strong><br>Owner: '+E(clean(v.owner))+'; Timing: '+E(clean(v.timing))+(v.measure?'<br>Success: '+E(clean(v.measure)):'')))+card('Unresolved Questions',bullets(x.unresolved_questions))+'</div>';
 document.getElementById('v2031Refresh').onclick=()=>window.openExecutiveStrategyV20(id);
 }catch(e){out.innerHTML=card('Strategy unavailable','<p>'+E(e.message)+'</p>')}
};
console.log('EXECUTIVE_NARRATIVE_COMPOSER_V20_3_1 loaded');
})();