/* HIGHSPOT_RESOURCE_CATALOG_V20_6_0 */
(function(){
'use strict';
let data=[],product='',category='';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const managed=new Set(['Highspot Catalog','Product Overview','Datasheet','Implementation Services','Battlecard','Competitive Intelligence','Highspot Video']);
const css=document.createElement('style');css.textContent=`
.v206-shell{margin-bottom:15px}.v206-tabs,.v206-products{display:flex;gap:6px;flex-wrap:wrap}.v206-tabs button.active,.v206-products button.active{background:var(--gold)!important;color:#210936!important}.v206-products{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));border:1px solid var(--line);border-radius:9px;overflow:hidden;margin:12px 0}.v206-products button{margin:0!important;border-radius:0!important;text-align:left}.v206-products small{display:block;color:var(--muted)}.v206-products button.active small{color:#210936}.v206-filter{display:grid;grid-template-columns:1fr 220px;gap:10px}.v206-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.v206-card{background:#180825;border:1px solid var(--line);border-left:4px solid var(--gold);border-radius:10px;padding:14px}.v206-card h3{margin:0 0 7px}.v206-card p{color:#eee}.v206-add-bottom{margin-top:24px;border-top:2px solid var(--gold);padding-top:16px}@media(max-width:900px){.v206-grid,.v206-filter{grid-template-columns:1fr}}
`;document.head.appendChild(css);
const form=()=>document.getElementById('resourceForm');
function moveForm(){const section=document.getElementById('resources'),f=form();if(!section||!f)return;let b=document.getElementById('v206Add');if(!b){b=document.createElement('div');b.id='v206Add';b.className='panel v206-add-bottom';b.innerHTML='<h2>Add or Edit Resource Link</h2>';section.appendChild(b)}if(f.parentElement!==b){const old=f.parentElement;f.classList.remove('panel');b.appendChild(f);if(old?.classList.contains('grid2')&&!old.children.length)old.remove()}}
function counts(field){const m=new Map();data.filter(x=>managed.has(x.category)).forEach(x=>{const k=x[field]||'Other';m.set(k,(m.get(k)||0)+1)});return m}
function card(x){return `<article class="v206-card"><h3>${E(x.title)}</h3><span class="pill">${E(x.category)}</span><span class="pill">${E(x.product||'Portfolio')}</span><p>${E(x.description||'Official Highspot resource')}</p><a class="btn primary" href="${E(x.url)}" target="_blank" rel="noopener noreferrer">Open in Highspot</a><button class="danger" onclick="deleteResource(${Number(x.id)})">Delete</button></article>`}
function draw(){const section=document.getElementById('resources'),view=document.getElementById('resourceView');if(!section||!view)return;let shell=document.getElementById('v206Shell');if(!shell){shell=document.createElement('div');shell.id='v206Shell';shell.className='panel v206-shell';section.querySelector('.hero')?.insertAdjacentElement('afterend',shell)}const pc=counts('product'),cc=counts('category'),total=[...pc.values()].reduce((a,b)=>a+b,0);shell.innerHTML=`<h2>Highspot Resource Catalog</h2><div class="v206-tabs"><button data-category="" class="${category?'':'active'}">All</button>${[...cc.keys()].sort().map(c=>`<button data-category="${E(c)}" class="${category===c?'active':''}">${E(c)} (${cc.get(c)})</button>`).join('')}</div><div class="v206-products"><button data-product="" class="${product?'':'active'}"><strong>All Products</strong><small>${total} resources</small></button>${[...pc.keys()].sort().map(p=>`<button data-product="${E(p)}" class="${product===p?'active':''}"><strong>${E(p)}</strong><small>${pc.get(p)} resources</small></button>`).join('')}</div><div class="v206-filter"><div class="field"><label>Search catalog</label><input id="v206Search" placeholder="Search title, product, category, or description"></div><div class="field"><label>Official Highspot</label><a class="btn" href="https://blackduck.highspot.com/spots/64c937f6a3538d4619854c67" target="_blank" rel="noopener noreferrer">Open Sales Materials</a></div></div>`;shell.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;draw()});shell.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>{product=b.dataset.product;draw()});shell.querySelector('#v206Search').oninput=render;moveForm();render()}
function render(){const view=document.getElementById('resourceView'),q=(document.getElementById('v206Search')?.value||'').toLowerCase();if(!view)return;const rows=data.filter(x=>managed.has(x.category)).filter(x=>(!product||(x.product||'Other')===product)&&(!category||x.category===category)&&JSON.stringify(x).toLowerCase().includes(q));view.innerHTML=rows.length?`<div class="v206-grid">${rows.map(card).join('')}</div>`:'<div class="empty">No matching Highspot resources.</div>'}
window.loadResources=async function(renderPage=true){const r=await fetch('/api/se-resources');if(!r.ok)throw new Error('Resource API failed with HTTP '+r.status);data=await r.json();window.RESOURCES=data;if(typeof RESOURCES!=='undefined')RESOURCES=data;if(renderPage)draw();if(typeof renderProducts==='function')renderProducts();return data};
const baseRoute=window.route;window.route=function(id){const result=baseRoute.apply(this,arguments);if(id==='resources')setTimeout(()=>window.loadResources(true),0);return result};
console.log('HIGHSPOT_RESOURCE_CATALOG_V20_6_0 loaded');
})();