const fs=require("fs"),path=require("path");
function parse(v){try{return v?JSON.parse(v):null}catch{return null}}
function cols(db,table){return new Set(db.prepare(`PRAGMA table_info(${table})`).all().map(x=>x.name))}
function value(row,name){return Object.prototype.hasOwnProperty.call(row,name)?row[name]:null}
function fileUrl(name){return name?"/exports/"+encodeURIComponent(name):null}
function coreSignature(row){const i=parse(row.input_json)||{};const core={partner:String(row.partner_name||"").trim().toLowerCase(),account:String(row.account_name||"").trim().toLowerCase(),objective:String(i.meeting_objective||"").trim().toLowerCase(),attendees:String(i.attendees||"").trim().toLowerCase(),context:String(i.known_context||"").replace(/\s+/g," ").trim().toLowerCase(),constraints:String(i.constraints||"").replace(/\s+/g," ").trim().toLowerCase(),duration:Number(i.duration_minutes||0)};return JSON.stringify(core)}
function completeness(db,row){let score=row.id/1000000;for(const k of ["result_json","research_json","partner_research_json","client_research_json","combined_research_json"])if(value(row,k))score+=1;try{score+=db.prepare("SELECT COUNT(*) n FROM research_exports WHERE call_prep_id=?").get(row.id).n*3}catch{}try{score+=db.prepare("SELECT COUNT(*) n FROM prep_query_audit WHERE call_prep_id=?").get(row.id).n}catch{}return score}
function latestExport(db,id){try{return db.prepare("SELECT * FROM research_exports WHERE call_prep_id=? ORDER BY id DESC LIMIT 1").get(id)||{}}catch{return {}}}
function mapRecord(db,row){const exp=latestExport(db,row.id);return{id:row.id,partner_name:row.partner_name,account_name:row.account_name,model:row.model,created_date:row.created_date,input:parse(row.input_json)||{},prepared_call:parse(row.result_json)||{},partner_research:parse(value(row,"partner_research_json")),client_research:parse(value(row,"client_research_json")),combined_research:parse(value(row,"combined_research_json"))||parse(value(row,"research_json")),account_plan_url:fileUrl(exp.report_path),strategy_brief_url:fileUrl(exp.deck_path),account_plan_name:exp.report_path||null,strategy_brief_name:exp.deck_path||null}}
function removeRecord(db,root,id){let exports=[];try{exports=db.prepare("SELECT * FROM research_exports WHERE call_prep_id=?").all(id)}catch{}for(const x of exports)for(const f of [x.report_path,x.deck_path])if(f){const full=path.join(root,"exports",f);try{if(fs.existsSync(full))fs.unlinkSync(full)}catch{}}try{db.prepare("DELETE FROM prep_query_audit WHERE call_prep_id=?").run(id)}catch{}try{db.prepare("DELETE FROM research_exports WHERE call_prep_id=?").run(id)}catch{}db.prepare("DELETE FROM call_prep_results WHERE id=?").run(id)}
module.exports=function(app,db,root){
 app.get("/api/history-v3",(req,res)=>{try{const rows=db.prepare("SELECT * FROM call_prep_results ORDER BY id DESC").all();res.json(rows.map(r=>mapRecord(db,r)))}catch(e){res.status(500).json({error:e.message})}});
 app.get("/api/history-v3/:id",(req,res)=>{try{const row=db.prepare("SELECT * FROM call_prep_results WHERE id=?").get(req.params.id);if(!row)return res.status(404).json({error:"Record not found"});res.json(mapRecord(db,row))}catch(e){res.status(500).json({error:e.message})}});
 app.delete("/api/history-v3/:id",(req,res)=>{try{removeRecord(db,root,Number(req.params.id));res.json({success:true})}catch(e){res.status(500).json({error:e.message})}});
 app.post("/api/history-v3/dedupe",(req,res)=>{try{const rows=db.prepare("SELECT * FROM call_prep_results ORDER BY id DESC").all(),groups=new Map();for(const row of rows){const sig=coreSignature(row);if(!groups.has(sig))groups.set(sig,[]);groups.get(sig).push(row)}const removed=[];for(const group of groups.values()){if(group.length<2)continue;group.sort((a,b)=>completeness(db,b)-completeness(db,a));for(const row of group.slice(1)){removed.push({id:row.id,partner:row.partner_name,account:row.account_name});removeRecord(db,root,row.id)}}res.json({success:true,removed_count:removed.length,removed})}catch(e){res.status(500).json({error:e.message})}});
};
