const crypto=require("crypto");
function parse(v){try{return v?JSON.parse(v):null}catch{return null}}
function sha(v){return crypto.createHash("sha256").update(String(v||"")).digest("hex")}
function number(stage){const m=String(stage||"").match(/^\s*(\d+)/);return m?Number(m[1]):0}
function has(text,re){return re.test(String(text||""))}
module.exports=function(app,db){
 app.get("/api/meeting-plan-v7/:id/pipeline",(req,res)=>{try{
  const rows=db.prepare("SELECT * FROM prep_query_audit WHERE call_prep_id=? ORDER BY id").all(req.params.id);
  const by=new Map(rows.map(x=>[number(x.stage),x]));
  const p=by.get(1)||{},c=by.get(2)||{},r=by.get(3)||{},s=by.get(4)||{};
  const stages=[
   {number:1,name:"Full Partner Research",framework:"GDIT-derived 18-step public-sector partner-channel framework",inputs:["Meeting input","Supplied evidence","Partner name","Prospective-client name for context only"],processing:"Analyzes the partner relationship, economics, access, capture and delivery roles, stakeholders, vehicles, enablement, governance and go-to-market motion.",output:"Standalone partner-research object",independence:"Does not consume prospective-client research output.",audit:p},
   {number:2,name:"Full Prospective-Client Research",framework:"Boeing-derived 15-step prospective-client framework",inputs:["Meeting input","Supplied evidence","Prospective-client name","Partner name for context only"],processing:"Analyzes the prospective client's mission or business, pain points, trends, initiatives, SWOT, executive themes, headwinds and tailwinds.",output:"Standalone prospective-client research object",independence:"Does not consume partner-research output.",audit:c},
   {number:3,name:"Research Reconciliation",framework:"Semantic reconciliation and evidence-quality framework",inputs:["Complete Step 1 output","Complete Step 2 output","Original meeting input"],processing:"Cross-references the independent research streams, resolves or flags conflicts, removes semantic duplicates, preserves evidence and identifies the partner/client/Black Duck intersection.",output:"One reconciled research object",independence:"This is the first stage where partner and client research are cross-referenced.",audit:r},
   {number:4,name:"Call Synthesis",framework:"Research-informed public-sector partner discovery framework",inputs:["Original meeting input","Complete Step 1 output","Complete Step 2 output","Complete Step 3 reconciled output"],processing:"Creates the final timed agenda, presenter script, Data-Insight-Question openings, discovery paths, objections, next step and facts to validate.",output:"Final Meeting Plan",independence:"Consumes both original research streams and the reconciled result.",audit:s}
  ].map(x=>{const q=String(x.audit.user_query||""),system=String(x.audit.system_query||""),response=String(x.audit.response_json||"");return{number:x.number,name:x.name,framework:x.framework,inputs:x.inputs,processing:x.processing,output:x.output,independence:x.independence,captured:!!x.audit.id,system_instruction_and_query_combined:!!(system&&q&&response),system_instruction_sha256:system?sha(system):null,query_input_sha256:q?sha(q):null,structured_output_sha256:response?sha(response):null,consumes_step_1:x.number>=3&&has(q,/FULL PARTNER|PARTNER RESEARCH|PARTNER-CHANNEL RESEARCH/i),consumes_step_2:x.number>=3&&has(q,/FULL CLIENT|CLIENT RESEARCH|PROSPECTIVE-CLIENT RESEARCH/i),consumes_step_3:x.number===4&&has(q,/RECONCILED RESEARCH/i),model:x.audit.model||null,created_date:x.audit.created_date||null}});
  res.json({record_id:Number(req.params.id),design_decision:"Steps 1 and 2 know both organization names for context, but remain analytically independent. Cross-reference begins in Step 3 to reduce circular reasoning and duplication.",stages,checks:{step_1_independent:!stages[0].consumes_step_2,step_2_independent:!stages[1].consumes_step_1,step_1_feeds_step_3:stages[2].consumes_step_1,step_2_feeds_step_3:stages[2].consumes_step_2,steps_1_2_3_feed_step_4:stages[3].consumes_step_1&&stages[3].consumes_step_2&&stages[3].consumes_step_3}})
 }catch(e){res.status(500).json({error:e.message})}});
};
